// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dog.proto

package io.grpc.examples.helloworld;

public interface GetDogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.GetDogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>int32 weight = 3;</code>
   * @return The weight.
   */
  int getWeight();
}
