// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dog.proto

package io.grpc.examples.helloworld;

public interface GetDogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.GetDogRequest)
    com.google.protobuf.MessageOrBuilder {
}
